services:
  public:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://backend:8000

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      API_BASE_URL: http://backend:8000
